# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divaGui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podatak',
            name='lokacija',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
